// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qszprjcrzyfczwetkuno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzenByamNyenlmY3p3ZXRrdW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODEyNzUsImV4cCI6MjA1NzM1NzI3NX0.BHJiwnL79pIdjdhz8b7YuglpRejdTUDFMG6DfFMqoTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);